version: "3.1"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: super-aggregator
      POSTGRES_PASSWORD: supersecret
    volumes:
    - "./tmp/data:/var/lib/postgresql/data"
    ports: ["5432:5432"]
