version: "3.1"
services:
  super-aggregator:
    restart: unless-stopped
    depends_on: [postgres]
    build: .
    command:
    - "-pg.host=postgres"
    - "-pg.user=super-aggregator"
    - "-pg.password=supersecret"
    environment:
      GIN_MODE: debug
    volumes:
    - "./views:/views:ro"
    ports: ["9000:9000"]
  postgres:
    restart: unless-stopped
    image: postgres:9.6
    environment:
      POSTGRES_USER: super-aggregator
      POSTGRES_PASSWORD: supersecret
    volumes:
    - "./tmp/data:/var/lib/postgresql/data"
    ports: ["5432:5432"]
